headers:
  Authorization:
    displayName: Authentication Token

    description: |
      The authentication token returned by a successful login.
      Sent as a `Bearer` token.

      `Bearer <token>`

    type: string
    required: true
